# Generated by Django 5.1.4 on 2024-12-22 19:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact person')),
                ('commercial_name', models.CharField(max_length=150, verbose_name='Commercial Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Primary Email')),
                ('email_facturation', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email facturation')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format : '+33 6 12 34 56 78' ou '06 12 34 56 78'", regex='^(?:\\+33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')])),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=100)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(choices=[('P', 'PROFORMA'), ('R', 'RECU'), ('F', 'FACTURE')], max_length=1)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='liste_client.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='liste_clien_name_f13040_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='liste_clien_email_818ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='liste_clien_invoice_87e09e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='liste_clien_custome_d03f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['paid'], name='liste_clien_paid_e43162_idx'),
        ),
    ]
